db:
  host: localhost
  port: "5432"
  user: postgres
  password: postgres
  dbname: feedbackbot

settings:
  srvaddress: ":8080"

jwt:
  accesssecret: "change-me-to-a-strong-secret"

auth_provider:
  baseurl: "https://auth.lavina.tech"
  clientid: ""
  clientsecret: ""
  redirecturi: "https://feedbackbot.lavina.tech/auth/callback"
